export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const NOT_FOUND = "NOT_FOUND";
export const BAD_REQUEST = "BAD_REQUEST";
export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const FORBIDDEN = "FORBIDDEN";
export const DATABASE_ERROR = "DATABASE_ERROR";
