services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - /app/node_modules

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./app:/app
      - /app/node_modules

  mongodb:
    image: mongo:8
    container_name: docsai-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: docsai
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
