import type { DocumentAccessAction } from "./documentAccess.actions.js";

export const DOCUMENT_AUTHORIZATION_MATRIX = Object.freeze({
  "GET /documents": "discover",
  "GET /documents/:id": "read",
  "GET /documents/:id/versions": "read",
  "GET /documents/:id/extraction": "read",
  "POST /documents/:id/extraction/retrigger": "reprocess",
  "GET /documents/:id/download": "download",
  "PATCH /documents/:id": "update",
  "PUT /documents/:id/replace": "replace",
  "POST /documents/:id/archive": "archive",
  "POST /documents/:id/restore": "restore",
  "DELETE /documents/:id": "delete",
  "DELETE /documents/:id/permanent": "delete",
  "GET /processing/:id/ocr/pages": "read",
  "GET /processing/:id/quality": "read",
  "GET /processing/:id/metadata/candidates": "read",
  "GET /processing/:id/relationships": "read",
  "GET /processing/:id/conflicts": "read",
  "POST /processing/:id/ocr/trigger": "reprocess",
  "POST /processing/:id/ocr/retry": "reprocess",
  "POST /processing/:id/quality/assess": "update",
  "POST /processing/:id/quality/review": "update",
  "POST /processing/:id/metadata/analyze": "reprocess",
  "POST /processing/:id/version-conflict/analyze": "reprocess",
  "POST /intent-query/analyze explicit document": "use_in_ai",
  "future policy management": "manage_access",
} satisfies Record<string, DocumentAccessAction>);
