import { Router } from "express";
import { authenticate } from "../../common/middlewares/authenticate.middleware.js";
import { tenantScoping } from "../../common/middlewares/tenantScoping.middleware.js";
import { Permission } from "../permissions/permissions.catalog.js";
import { requirePermission } from "../permissions/permissions.middleware.js";
import { billingOperationController, billingSummaryController, cancellationController, invoiceDetailController, invoiceLinksController, invoiceListController, portalSessionController, reactivationController, refundDetailController, refundListController, refundRequestController, subscriptionChangeController, subscriptionChangePreviewController } from "./tenant-billing.controller.js";

const router = Router();
router.use(authenticate, tenantScoping);
const billingDenialAudit = { denialAuditAction: "BILLING_AUTHORIZATION_DENIED" as const, resourceType: "Permission" as const };
router.get("/summary", requirePermission(Permission.BILLING_READ, billingDenialAudit), billingSummaryController);
router.post("/portal-sessions", requirePermission(Permission.BILLING_MANAGE, billingDenialAudit), portalSessionController);
router.post("/subscription-change-previews", requirePermission(Permission.BILLING_MANAGE, billingDenialAudit), subscriptionChangePreviewController);
router.post("/subscription-changes", requirePermission(Permission.BILLING_MANAGE, billingDenialAudit), subscriptionChangeController);
router.post("/cancellations", requirePermission(Permission.BILLING_MANAGE, billingDenialAudit), cancellationController);
router.post("/reactivations", requirePermission(Permission.BILLING_MANAGE, billingDenialAudit), reactivationController);
router.get("/operations/:operationId", requirePermission(Permission.BILLING_READ, billingDenialAudit), billingOperationController);
router.post("/refund-requests", requirePermission(Permission.BILLING_MANAGE, billingDenialAudit), refundRequestController);
router.get("/refund-requests", requirePermission(Permission.BILLING_READ, billingDenialAudit), refundListController);
router.get("/refund-requests/:refundId", requirePermission(Permission.BILLING_READ, billingDenialAudit), refundDetailController);
router.get("/invoices", requirePermission(Permission.BILLING_READ, billingDenialAudit), invoiceListController);
router.get("/invoices/:invoiceId", requirePermission(Permission.BILLING_READ, billingDenialAudit), invoiceDetailController);
router.get("/invoices/:invoiceId/links", requirePermission(Permission.BILLING_READ, billingDenialAudit), invoiceLinksController);
export default router;
