import type { AnalyzeQueryInput, IntentClassValue, QueryPlan } from "./intentQuery.types.js";
import { AnalyzeQueryInputSchema, QueryPlanSchema } from "./intentQuery.types.js";
import { deriveQueryRoute } from "./intentQuery.route.js";
import { AppError } from "../../common/errors/AppError.js";
import { INTENT_QUERY_VALIDATION_ERROR } from "../../common/errors/errorCodes.js";

/**
 * Validates request payload for query analysis.
 */
export function validateAnalyzeQuery(input: unknown): AnalyzeQueryInput {
  const result = AnalyzeQueryInputSchema.safeParse(input);
  if (!result.success) {
    throw new AppError(
      400,
      INTENT_QUERY_VALIDATION_ERROR,
      "Validation failed: " + result.error.issues.map(i => `${i.path.join(".")}: ${i.message}`).join(", "),
      result.error.issues
    );
  }
  return result.data;
}

/**
 * Safely parses and normalizes the query plan generated by LLM or fallback.
 * Limits array sizes and enforces sanitization boundaries.
 */
export function validateAndNormalizeQueryPlan(
  raw: unknown,
  originalQuestion: string,
  detectedLanguage: "ar" | "en" | "mixed",
  promptVersion: string,
  modelVersion: string,
  latencyMs: number,
  tokensUsed: number,
  estimatedCost: number,
  fallbackUsed = false
): QueryPlan {
  const rawObject = typeof raw === "object" && raw !== null ? raw : {};
  const rawIntent = (rawObject as { detectedIntent?: unknown }).detectedIntent ?? "knowledge_question";
  const rawClarification = Boolean((rawObject as { clarificationNeeded?: unknown }).clarificationNeeded);
  const rawSocialSubtype = (rawObject as { socialSubtype?: unknown }).socialSubtype;

  const rawWithDefaults = {
    schemaVersion: "1.0.0",
    normalizedQuestion: originalQuestion.trim(),
    originalQuestion,
    temporalConstraints: [],
    referencedDocumentIds: [],
    referencedDocumentTitles: [],
    departments: [],
    categories: [],
    exactTerms: [],
    semanticQueries: [],
    keywordQueries: [],
    isFollowUp: false,
    conversationContextUsed: false,
    promptVersion,
    modelVersion,
    processingMetadata: {
      tokensUsed,
      latencyMs,
      estimatedCost,
      fallbackUsed,
    },
    ...rawObject,
    // Providers commonly emit null for fields that only apply to another
    // intent. Treat null like omission so an otherwise valid RAG plan does not
    // lose its authorized title ids and query expansions wholesale.
    socialSubtype: rawSocialSubtype == null ? "acknowledgement" : rawSocialSubtype,
    // Route is derived deterministically from intent + clarification state and
    // is never taken verbatim from model output.
    route: deriveQueryRoute(rawIntent as IntentClassValue, rawClarification),
  };

  // Try to parse/validate the raw structure
  const parsed = QueryPlanSchema.safeParse(rawWithDefaults);
  if (parsed.success) {
    // Normal case: valid schema returned from LLM
    const plan = parsed.data;
    // Enforce array size constraints
    return {
      ...plan,
      originalQuestion,
      route: deriveQueryRoute(plan.detectedIntent, plan.clarificationNeeded),
      entities: plan.entities.slice(0, 50),
      temporalConstraints: plan.temporalConstraints.slice(0, 10),
      referencedDocumentIds: plan.referencedDocumentIds.slice(0, 20),
      referencedDocumentTitles: plan.referencedDocumentTitles.slice(0, 20),
      departments: plan.departments.slice(0, 20),
      categories: plan.categories.slice(0, 20),
      exactTerms: plan.exactTerms.slice(0, 30),
      semanticQueries: plan.semanticQueries.slice(0, 10),
      keywordQueries: plan.keywordQueries.slice(0, 10),
      promptVersion,
      modelVersion,
      processingMetadata: {
        tokensUsed,
        latencyMs,
        estimatedCost,
        fallbackUsed,
      },
    };
  }

  // Fallback case: schema-invalid LLM response or failure
  return {
    schemaVersion: "1.0.0",
    normalizedQuestion: originalQuestion.trim(),
    originalQuestion,
    language: detectedLanguage,
    detectedIntent: "knowledge_question",
    intentConfidence: 0.3,
    entities: [],
    temporalConstraints: [],
    referencedDocumentIds: [],
    referencedDocumentTitles: [],
    departments: [],
    categories: [],
    exactTerms: [],
    semanticQueries: [
      {
        text: originalQuestion,
        language: detectedLanguage,
        weight: 1.0,
      },
    ],
    keywordQueries: [],
    clarificationNeeded: false,
    clarification: null,
    route: "rag",
    socialSubtype: "acknowledgement",
    isFollowUp: false,
    conversationContextUsed: false,
    promptVersion,
    modelVersion,
    processingMetadata: {
      tokensUsed,
      latencyMs,
      estimatedCost,
      fallbackUsed: true,
    },
  };
}
