import { Permission } from "../../permissions/permissions.catalog.js";
import type { GuideFlow, GuideStepTemplate, GuidePlacement, GuideInteraction } from "./guide.contracts.js";

function step(
  stepId: string,
  order: number,
  titleKey: string,
  instructionKey: string,
  targetId: string,
  placement: GuidePlacement = "auto",
  interaction: GuideInteraction = "click",
  completionEvent: "click" | "route_change" | "value_present" | "manual" = "click",
  routeMatch?: string,
  optional = false,
  fallbackOnMissing: "skip" | "stop" | "wait" = "skip",
  waitMs?: number,
): GuideStepTemplate {
  return {
    stepId,
    order,
    titleKey,
    instructionKey,
    target: { targetId, optional },
    placement,
    interaction,
    completion: { event: completionEvent, routeMatch },
    fallback: { onMissing: fallbackOnMissing, waitMs },
  };
}

export const GUIDE_FLOWS: readonly GuideFlow[] = [
  {
    flowId: "documents.upload",
    titleKey: "copilot.guide.documents.upload.title",
    requiredPermissions: [Permission.DOCUMENTS_CREATE],
    entryRoute: "/dashboard/documents",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.documents.upload.step1.title",
        "copilot.guide.documents.upload.step1.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.documents.upload.step2.title",
        "copilot.guide.documents.upload.step2.instruction",
        "documents-upload-button",
        "top",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.documents.upload.step3.title",
        "copilot.guide.documents.upload.step3.instruction",
        "documents-dropzone",
        "top",
        "click",
        "click",
      ),
      step(
        "step-4",
        4,
        "copilot.guide.documents.upload.step4.title",
        "copilot.guide.documents.upload.step4.instruction",
        "documents-title-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-5",
        5,
        "copilot.guide.documents.upload.step5.title",
        "copilot.guide.documents.upload.step5.instruction",
        "documents-description-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-6",
        6,
        "copilot.guide.documents.upload.step6.title",
        "copilot.guide.documents.upload.step6.instruction",
        "documents-tags-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-7",
        7,
        "copilot.guide.documents.upload.step7.title",
        "copilot.guide.documents.upload.step7.instruction",
        "documents-upload-submit",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "documents.search",
    titleKey: "copilot.guide.documents.search.title",
    requiredPermissions: [Permission.DOCUMENTS_READ],
    entryRoute: "/dashboard/documents",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.documents.search.step1.title",
        "copilot.guide.documents.search.step1.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.documents.search.step2.title",
        "copilot.guide.documents.search.step2.instruction",
        "documents-search-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.documents.search.step3.title",
        "copilot.guide.documents.search.step3.instruction",
        "documents-search-button",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "documents.delete",
    titleKey: "copilot.guide.documents.delete.title",
    requiredPermissions: [Permission.DOCUMENTS_DELETE],
    entryRoute: "/dashboard/documents",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.documents.delete.step1.title",
        "copilot.guide.documents.delete.step1.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.documents.delete.step2.title",
        "copilot.guide.documents.delete.step2.instruction",
        "documents-table-row-menu",
        "start",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.documents.delete.step3.title",
        "copilot.guide.documents.delete.step3.instruction",
        "documents-table-row-menu",
        "start",
        "click",
        "click",
        undefined,
        true,
        "wait",
        5000,
      ),
    ],
  },
  {
    flowId: "users.invite",
    titleKey: "copilot.guide.users.invite.title",
    requiredPermissions: [Permission.USERS_CREATE],
    entryRoute: "/dashboard/users",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.users.invite.step1.title",
        "copilot.guide.users.invite.step1.instruction",
        "nav-users",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/users",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.users.invite.step2.title",
        "copilot.guide.users.invite.step2.instruction",
        "users-invite-button",
        "top",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.users.invite.step3.title",
        "copilot.guide.users.invite.step3.instruction",
        "users-invite-form-name",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-4",
        4,
        "copilot.guide.users.invite.step4.title",
        "copilot.guide.users.invite.step4.instruction",
        "users-invite-form-email",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-5",
        5,
        "copilot.guide.users.invite.step5.title",
        "copilot.guide.users.invite.step5.instruction",
        "users-invite-form-role",
        "top",
        "click",
        "click",
      ),
      step(
        "step-6",
        6,
        "copilot.guide.users.invite.step6.title",
        "copilot.guide.users.invite.step6.instruction",
        "users-invite-form-submit",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "knowledgeBase.build",
    titleKey: "copilot.guide.knowledgeBase.build.title",
    requiredPermissions: [Permission.DOCUMENTS_CREATE],
    entryRoute: "/dashboard/documents",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.knowledgeBase.build.step1.title",
        "copilot.guide.knowledgeBase.build.step1.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.knowledgeBase.build.step2.title",
        "copilot.guide.knowledgeBase.build.step2.instruction",
        "documents-upload-button",
        "top",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.knowledgeBase.build.step3.title",
        "copilot.guide.knowledgeBase.build.step3.instruction",
        "documents-dropzone",
        "top",
        "click",
        "click",
      ),
      step(
        "step-4",
        4,
        "copilot.guide.knowledgeBase.build.step4.title",
        "copilot.guide.knowledgeBase.build.step4.instruction",
        "documents-title-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-5",
        5,
        "copilot.guide.knowledgeBase.build.step5.title",
        "copilot.guide.knowledgeBase.build.step5.instruction",
        "documents-description-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-6",
        6,
        "copilot.guide.knowledgeBase.build.step6.title",
        "copilot.guide.knowledgeBase.build.step6.instruction",
        "documents-tags-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-7",
        7,
        "copilot.guide.knowledgeBase.build.step7.title",
        "copilot.guide.knowledgeBase.build.step7.instruction",
        "documents-upload-submit",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "taxonomy.manage",
    titleKey: "copilot.guide.taxonomy.manage.title",
    requiredPermissions: [Permission.COMPANY_SETTINGS_READ],
    entryRoute: "/dashboard/settings/document-taxonomy",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.taxonomy.manage.step1.title",
        "copilot.guide.taxonomy.manage.step1.instruction",
        "nav-document-taxonomy",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/settings/document-taxonomy",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.taxonomy.manage.step2.title",
        "copilot.guide.taxonomy.manage.step2.instruction",
        "taxonomy-create-button",
        "top",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.taxonomy.manage.step3.title",
        "copilot.guide.taxonomy.manage.step3.instruction",
        "taxonomy-create-button",
        "top",
        "observe",
        "manual",
        undefined,
        true,
        "wait",
        5000,
      ),
    ],
  },
  {
    flowId: "settings.open",
    titleKey: "copilot.guide.settings.open.title",
    requiredPermissions: [Permission.COMPANY_SETTINGS_READ],
    entryRoute: "/dashboard/settings",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.settings.open.step1.title",
        "copilot.guide.settings.open.step1.instruction",
        "nav-settings",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/settings",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.settings.open.step2.title",
        "copilot.guide.settings.open.step2.instruction",
        "settings-profile-section",
        "top",
        "observe",
        "manual",
      ),
    ],
  },
  {
    flowId: "billing.open",
    titleKey: "copilot.guide.billing.open.title",
    requiredPermissions: [Permission.BILLING_READ],
    entryRoute: "/dashboard/settings/billing",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.billing.open.step1.title",
        "copilot.guide.billing.open.step1.instruction",
        "nav-billing",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/settings/billing",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.billing.open.step2.title",
        "copilot.guide.billing.open.step2.instruction",
        "settings-billing-tab",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "chat.ask",
    titleKey: "copilot.guide.chat.ask.title",
    requiredPermissions: [Permission.CHAT_READ],
    entryRoute: "/dashboard/chat",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.chat.ask.step1.title",
        "copilot.guide.chat.ask.step1.instruction",
        "nav-chat",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/chat",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.chat.ask.step2.title",
        "copilot.guide.chat.ask.step2.instruction",
        "chat-message-input",
        "bottom",
        "input",
        "value_present",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.chat.ask.step3.title",
        "copilot.guide.chat.ask.step3.instruction",
        "chat-send-button",
        "bottom",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "documents.archive",
    titleKey: "copilot.guide.documents.archive.title",
    requiredPermissions: [Permission.DOCUMENTS_ARCHIVE],
    entryRoute: "/dashboard/documents",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.documents.archive.step1.title",
        "copilot.guide.documents.archive.step1.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.documents.archive.step2.title",
        "copilot.guide.documents.archive.step2.instruction",
        "documents-search-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.documents.archive.step3.title",
        "copilot.guide.documents.archive.step3.instruction",
        "documents-view-button",
        "start",
        "click",
        "click",
      ),
      step(
        "step-4",
        4,
        "copilot.guide.documents.archive.step4.title",
        "copilot.guide.documents.archive.step4.instruction",
        "documents-drawer-archive",
        "top",
        "click",
        "click",
        undefined,
        true,
        "wait",
        5000,
      ),
    ],
  },
  {
    flowId: "documents.restore",
    titleKey: "copilot.guide.documents.restore.title",
    requiredPermissions: [Permission.DOCUMENTS_ARCHIVE],
    entryRoute: "/dashboard/documents",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.documents.restore.step1.title",
        "copilot.guide.documents.restore.step1.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.documents.restore.step2.title",
        "copilot.guide.documents.restore.step2.instruction",
        "documents-archived-filter",
        "top",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.documents.restore.step3.title",
        "copilot.guide.documents.restore.step3.instruction",
        "documents-view-button",
        "start",
        "click",
        "click",
      ),
      step(
        "step-4",
        4,
        "copilot.guide.documents.restore.step4.title",
        "copilot.guide.documents.restore.step4.instruction",
        "documents-drawer-restore",
        "top",
        "click",
        "click",
        undefined,
        true,
        "wait",
        5000,
      ),
    ],
  },
  {
    flowId: "documents.replace",
    titleKey: "copilot.guide.documents.replace.title",
    requiredPermissions: [Permission.DOCUMENTS_UPDATE],
    entryRoute: "/dashboard/documents",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.documents.replace.step1.title",
        "copilot.guide.documents.replace.step1.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.documents.replace.step2.title",
        "copilot.guide.documents.replace.step2.instruction",
        "documents-search-input",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.documents.replace.step3.title",
        "copilot.guide.documents.replace.step3.instruction",
        "documents-view-button",
        "start",
        "click",
        "click",
      ),
      step(
        "step-4",
        4,
        "copilot.guide.documents.replace.step4.title",
        "copilot.guide.documents.replace.step4.instruction",
        "documents-drawer-replace",
        "top",
        "click",
        "click",
      ),
      step(
        "step-5",
        5,
        "copilot.guide.documents.replace.step5.title",
        "copilot.guide.documents.replace.step5.instruction",
        "documents-drawer-replace-file",
        "top",
        "click",
        "click",
      ),
      step(
        "step-6",
        6,
        "copilot.guide.documents.replace.step6.title",
        "copilot.guide.documents.replace.step6.instruction",
        "documents-drawer-replace-submit",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "documents.failedReview",
    titleKey: "copilot.guide.documents.failedReview.title",
    requiredPermissions: [Permission.COMPANY_SETTINGS_READ],
    entryRoute: "/dashboard/processing-failed",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.documents.failedReview.step1.title",
        "copilot.guide.documents.failedReview.step1.instruction",
        "nav-processing-failed",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/processing-failed",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.documents.failedReview.step2.title",
        "copilot.guide.documents.failedReview.step2.instruction",
        "page-heading-processing-failed",
        "top",
        "observe",
        "manual",
      ),
    ],
  },
  {
    flowId: "users.resendInvitation",
    titleKey: "copilot.guide.users.resendInvitation.title",
    requiredPermissions: [Permission.USERS_CREATE],
    entryRoute: "/dashboard/users",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.users.resendInvitation.step1.title",
        "copilot.guide.users.resendInvitation.step1.instruction",
        "nav-users",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/users",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.users.resendInvitation.step2.title",
        "copilot.guide.users.resendInvitation.step2.instruction",
        "users-resend-button",
        "start",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.users.resendInvitation.step3.title",
        "copilot.guide.users.resendInvitation.step3.instruction",
        "users-resend-button",
        "start",
        "observe",
        "manual",
        undefined,
        true,
        "wait",
        5000,
      ),
    ],
  },
  {
    flowId: "users.revokeInvitation",
    titleKey: "copilot.guide.users.revokeInvitation.title",
    requiredPermissions: [Permission.USERS_DELETE],
    entryRoute: "/dashboard/users",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.users.revokeInvitation.step1.title",
        "copilot.guide.users.revokeInvitation.step1.instruction",
        "nav-users",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/users",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.users.revokeInvitation.step2.title",
        "copilot.guide.users.revokeInvitation.step2.instruction",
        "users-revoke-button",
        "start",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.users.revokeInvitation.step3.title",
        "copilot.guide.users.revokeInvitation.step3.instruction",
        "users-revoke-button",
        "start",
        "observe",
        "manual",
        undefined,
        true,
        "wait",
        5000,
      ),
    ],
  },
  {
    flowId: "users.remove",
    titleKey: "copilot.guide.users.remove.title",
    requiredPermissions: [Permission.USERS_DELETE],
    entryRoute: "/dashboard/users",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.users.remove.step1.title",
        "copilot.guide.users.remove.step1.instruction",
        "nav-users",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/users",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.users.remove.step2.title",
        "copilot.guide.users.remove.step2.instruction",
        "users-delete-button",
        "start",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.users.remove.step3.title",
        "copilot.guide.users.remove.step3.instruction",
        "users-delete-button",
        "start",
        "observe",
        "manual",
        undefined,
        true,
        "wait",
        5000,
      ),
    ],
  },
  {
    flowId: "roles.create",
    titleKey: "copilot.guide.roles.create.title",
    requiredPermissions: [Permission.ROLES_CREATE],
    entryRoute: "/dashboard/roles",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.roles.create.step1.title",
        "copilot.guide.roles.create.step1.instruction",
        "nav-roles",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/roles",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.roles.create.step2.title",
        "copilot.guide.roles.create.step2.instruction",
        "roles-create-button",
        "top",
        "click",
        "click",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.roles.create.step3.title",
        "copilot.guide.roles.create.step3.instruction",
        "roles-create-name",
        "top",
        "input",
        "value_present",
      ),
      step(
        "step-4",
        4,
        "copilot.guide.roles.create.step4.title",
        "copilot.guide.roles.create.step4.instruction",
        "roles-create-submit",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "settings.updateProfile",
    titleKey: "copilot.guide.settings.updateProfile.title",
    requiredPermissions: [Permission.COMPANY_SETTINGS_UPDATE],
    entryRoute: "/dashboard/settings",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.settings.updateProfile.step1.title",
        "copilot.guide.settings.updateProfile.step1.instruction",
        "nav-settings",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/settings",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.settings.updateProfile.step2.title",
        "copilot.guide.settings.updateProfile.step2.instruction",
        "settings-profile-section",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.settings.updateProfile.step3.title",
        "copilot.guide.settings.updateProfile.step3.instruction",
        "settings-profile-save",
        "top",
        "click",
        "click",
      ),
    ],
  },
  {
    flowId: "usage.view",
    titleKey: "copilot.guide.usage.view.title",
    requiredPermissions: [Permission.BILLING_READ],
    entryRoute: "/company/usage",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.usage.view.step1.title",
        "copilot.guide.usage.view.step1.instruction",
        "nav-company-usage",
        "auto",
        "navigate",
        "route_change",
        "/company/usage",
      ),
      step(
        "step-2",
        2,
        "copilot.guide.usage.view.step2.title",
        "copilot.guide.usage.view.step2.instruction",
        "page-heading-usage",
        "top",
        "observe",
        "manual",
      ),
    ],
  },
  {
    flowId: "platform.tour",
    titleKey: "copilot.guide.platform.tour.title",
    requiredPermissions: [],
    entryRoute: "/dashboard",
    steps: [
      step(
        "step-1",
        1,
        "copilot.guide.platform.tour.step1.title",
        "copilot.guide.platform.tour.step1.instruction",
        "nav-overview",
        "auto",
        "navigate",
        "route_change",
        "/dashboard",
        false,
        "wait",
        8000,
      ),
      step(
        "step-2",
        2,
        "copilot.guide.platform.tour.step2.title",
        "copilot.guide.platform.tour.step2.instruction",
        "page-heading-overview",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-3",
        3,
        "copilot.guide.platform.tour.step3.title",
        "copilot.guide.platform.tour.step3.instruction",
        "nav-documents",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/documents",
        false,
        "wait",
        8000,
      ),
      step(
        "step-4",
        4,
        "copilot.guide.platform.tour.step4.title",
        "copilot.guide.platform.tour.step4.instruction",
        "page-heading-documents",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-5",
        5,
        "copilot.guide.platform.tour.step5.title",
        "copilot.guide.platform.tour.step5.instruction",
        "documents-upload-button",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-6",
        6,
        "copilot.guide.platform.tour.step6.title",
        "copilot.guide.platform.tour.step6.instruction",
        "nav-users",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/users",
        false,
        "wait",
        8000,
      ),
      step(
        "step-7",
        7,
        "copilot.guide.platform.tour.step7.title",
        "copilot.guide.platform.tour.step7.instruction",
        "page-heading-users",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-8",
        8,
        "copilot.guide.platform.tour.step8.title",
        "copilot.guide.platform.tour.step8.instruction",
        "nav-roles",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/roles",
        false,
        "wait",
        8000,
      ),
      step(
        "step-9",
        9,
        "copilot.guide.platform.tour.step9.title",
        "copilot.guide.platform.tour.step9.instruction",
        "page-heading-roles",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-10",
        10,
        "copilot.guide.platform.tour.step10.title",
        "copilot.guide.platform.tour.step10.instruction",
        "nav-settings",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/settings",
        false,
        "wait",
        8000,
      ),
      step(
        "step-11",
        11,
        "copilot.guide.platform.tour.step11.title",
        "copilot.guide.platform.tour.step11.instruction",
        "page-heading-settings",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-12",
        12,
        "copilot.guide.platform.tour.step12.title",
        "copilot.guide.platform.tour.step12.instruction",
        "nav-document-taxonomy",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/settings/document-taxonomy",
        false,
        "wait",
        8000,
      ),
      step(
        "step-13",
        13,
        "copilot.guide.platform.tour.step13.title",
        "copilot.guide.platform.tour.step13.instruction",
        "page-heading-document-taxonomy",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-14",
        14,
        "copilot.guide.platform.tour.step14.title",
        "copilot.guide.platform.tour.step14.instruction",
        "nav-billing",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/settings/billing",
        false,
        "wait",
        8000,
      ),
      step(
        "step-15",
        15,
        "copilot.guide.platform.tour.step15.title",
        "copilot.guide.platform.tour.step15.instruction",
        "page-heading-billing",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-16",
        16,
        "copilot.guide.platform.tour.step16.title",
        "copilot.guide.platform.tour.step16.instruction",
        "nav-company-usage",
        "auto",
        "navigate",
        "route_change",
        "/company/usage",
        false,
        "wait",
        8000,
      ),
      step(
        "step-17",
        17,
        "copilot.guide.platform.tour.step17.title",
        "copilot.guide.platform.tour.step17.instruction",
        "page-heading-usage",
        "top",
        "observe",
        "manual",
      ),
      step(
        "step-18",
        18,
        "copilot.guide.platform.tour.step18.title",
        "copilot.guide.platform.tour.step18.instruction",
        "nav-chat",
        "auto",
        "navigate",
        "route_change",
        "/dashboard/chat",
        false,
        "wait",
        8000,
      ),
      step(
        "step-19",
        19,
        "copilot.guide.platform.tour.step19.title",
        "copilot.guide.platform.tour.step19.instruction",
        "page-heading-chat",
        "top",
        "observe",
        "manual",
      ),
    ],
  },
] as const;

export function createGuideFlowRegistry(): Map<string, GuideFlow> {
  const map = new Map<string, GuideFlow>();
  for (const flow of GUIDE_FLOWS) {
    if (map.has(flow.flowId)) {
      throw new Error(`Duplicate guide flow id: ${flow.flowId}`);
    }
    map.set(flow.flowId, flow);
  }
  return map;
}

export function getGuideFlow(flowId: string): GuideFlow | undefined {
  return createGuideFlowRegistry().get(flowId);
}

export function getAllGuideFlows(): GuideFlow[] {
  return Array.from(createGuideFlowRegistry().values());
}