/**
 * Typed mirror of DESIGN.md's color tokens, for the handful of places that
 * can't consume a Tailwind class — chart libraries (recharts/chart.js),
 * canvas drawing, or inline `style` props that need a literal value.
 *
 * Everywhere else, prefer the Tailwind utilities generated by
 * `app/globals.css` (e.g. `bg-primary`, `text-on-surface-variant`) over
 * importing these constants directly, so there is exactly one source of
 * truth for a given token.
 *
 * Keep this file's values in sync with DESIGN.md and globals.css.
 */

export const colors = {
  surface: "#f7f9fc",
  surfaceDim: "#d8dadd",
  surfaceBright: "#f7f9fc",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f2f4f7",
  surfaceContainer: "#eceef1",
  surfaceContainerHigh: "#e6e8eb",
  surfaceContainerHighest: "#e0e3e6",
  onSurface: "#191c1e",
  onSurfaceVariant: "#43474c",
  inverseSurface: "#2d3133",
  inverseOnSurface: "#eff1f4",
  outline: "#73777d",
  outlineVariant: "#c3c7cd",
  surfaceTint: "#486176",

  primary: "#001524",
  onPrimary: "#ffffff",
  primaryContainer: "#0f2a3d",
  onPrimaryContainer: "#7992a9",
  inversePrimary: "#b0c9e2",

  secondary: "#3f627b",
  onSecondary: "#ffffff",
  secondaryContainer: "#bde1fe",
  onSecondaryContainer: "#41657d",

  tertiary: "#001617",
  onTertiary: "#ffffff",
  tertiaryContainer: "#002d2e",
  onTertiaryContainer: "#0a9fa1",

  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",

  warning: "#b45309",
  onWarning: "#ffffff",
  warningContainer: "#fef3c7",
  onWarningContainer: "#92400e",

  success: "#047857",
  onSuccess: "#ffffff",
  successContainer: "#d1fae5",
  onSuccessContainer: "#065f46",

  info: "#1d4ed8",
  onInfo: "#ffffff",
  infoContainer: "#dbeafe",
  onInfoContainer: "#1e40af",

  background: "#f7f9fc",
  onBackground: "#191c1e",
  surfaceVariant: "#e0e3e6",
} as const;

export type ColorToken = keyof typeof colors;

/** Ordered categorical palette for charts (queries-over-time, bar charts, etc). */
export const chartSeriesColors: readonly string[] = [
  colors.primary,
  colors.onTertiaryContainer, // accent teal — DESIGN.md "spark of the AI assistant"
  colors.secondary,
  colors.error,
  colors.outline,
];

export const radius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  "2xl": 24,
  full: 9999,
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  "2xl": 48,
} as const;

export type TypographyRole =
  | "display-lg"
  | "headline-lg"
  | "headline-lg-mobile"
  | "headline-md"
  | "title-lg"
  | "body-lg"
  | "body-md"
  | "body-sm"
  | "label-md"
  | "label-sm";

/** Tailwind utility class for a given DESIGN.md typography role. */
export function typographyClass(role: TypographyRole): string {
  return `text-${role}`;
}
