import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: false,
    environment: "node",
    setupFiles: ["./vitest.setup.db-guard.ts"],
    env: {
      NODE_ENV: "test",
      MONGODB_URI: "mongodb://localhost:27017/documind-test",
      REDIS_URL: "redis://localhost:6379",
      APP_FRONTEND_URL: "http://example.com",
      JWT_SECRET: "test-jwt-secret-0123456789abcdefghijklmnopqrstuv",
      JWT_REFRESH_SECRET: "test-jwt-refresh-secret-0123456789abcdefghijk",
      EMAIL_VERIFICATION_JWT_SECRET: "test-email-verification-secret-012345678",
      PASSWORD_RESET_JWT_SECRET: "test-password-reset-secret-01234567890",
      EMAIL_WEBHOOK_SECRET: "test-email-webhook-secret-01234567890abc",
      NOTIFICATION_SOCKET_SERVICE_TOKEN: "test-notification-socket-token-012345678",
    },
    // The official API runner provisions one disposable replica-set database.
    // Persistence suites reset shared collections, so files must not run in
    // parallel against that single database.
    fileParallelism: false,
    hookTimeout: 30_000,
    testTimeout: 30_000,
    include: [
      "src/modules/billing/**/*.test.ts",
      "src/modules/checkout/__tests__/checkout.service.test.ts",
      "src/modules/checkout/__tests__/checkout-session-sync.service.test.ts",
      "src/modules/reconciliation/__tests__/provider-reconciliation.service.test.ts",
      "src/modules/auth/__tests__/*.test.ts",
      "src/db/__tests__/*.test.ts",
      "src/db/models/billing-models.test.ts",
      "src/scripts/__tests__/*.test.ts",
      "src/modules/imports/__tests__/*.test.ts",
      "src/modules/imports/ports/__tests__/*.test.ts",
      "src/modules/imports/services/__tests__/*.test.ts",
      "src/__tests__/*.test.ts",
      "src/modules/agents/__tests__/*.test.ts",
      "src/modules/entitlement/__tests__/*.test.ts",
      "src/modules/entitlement/ports/fakes/__tests__/*.test.ts",
      "src/modules/processing/chunking/__tests__/*.test.ts",
      "src/modules/processing/indexing/__tests__/*.test.ts",
      "src/modules/processing-progress/__tests__/*.test.ts",
      "src/modules/notifications/__tests__/*.test.ts",
      "src/modules/copilot/__tests__/*.test.ts",
      "src/modules/public/__tests__/*.test.ts",
      "src/modules/retrieval/ports/__tests__/*.test.ts",
      "src/providers/bedrock/__tests__/*.test.ts",
      "src/providers/stt/__tests__/*.test.ts",
      "src/modules/chat/__tests__/*.test.ts",
      "src/providers/embedding/__tests__/*.test.ts",
      "src/providers/keyword-index/__tests__/*.test.ts",
      "src/providers/vector-index/__tests__/*.test.ts",
    ],
    exclude: [
      "**/node_modules/**",
      "**/dist/**",
      "**/subscription-provisioning.contract.test.ts",
      "src/modules/chat/__tests__/chat.productionWorkflow.e2e.test.ts",
      "**/indexing/__tests__/indexing.tenant-isolation.test.ts",
      "src/modules/copilot/__tests__/classifierFallback.test.ts",
      "src/modules/copilot/__tests__/copilotSupervisorDecision.test.ts",
      "src/modules/copilot/__tests__/eval.test.ts",
      "src/modules/public/__tests__/public.routes.test.ts",
    ],
  },
});
